parsed memory info w/ example, name change
lydiachoi/test-percentage-visualizer pull request #21
Opened 2019-11-20 07:39 UTC by lydiachoi

2019-11-20 17:51 UTC, jregchiu requested changes

2019-11-20 17:51 UTC, jregchiu commented on parsers/memory.awk
> +  print ",Commit, (Pass/fail, Test Class, Heap Usage in MB)* \n";
Not sure what we need in terms of info for the visualization (@xavierdelacruz or @shannonjanehogan can comment on that) but I think the header should look like `Commit, Pass/fail, Test Class, Heap Usage in MB` without the leading comma or parentheses

2019-11-20 19:15 UTC, xavierdelacruz commented on parsers/memory.awk
> +  print ",Commit, (Pass/fail, Test Class, Heap Usage in MB)* \n";
@lydiachoi, for headers, we don’t want to have spaces between commas. For example, the header would be Commit,Pass/Fail,Test Class,Heap Usage in MB

2019-11-21 02:48 UTC, lydiachoi commented on parsers/memory.awk
> +  print ",Commit, (Pass/fail, Test Class, Heap Usage in MB)* \n";
will change the spacing, but the leading comma gets edited out in the final csv!

2019-11-21 03:02 UTC, xavierdelacruz approved these changes
Looks good, let’s see what Shannon comes up with the dynamic one

2019-11-21 03:06 UTC, lydiachoi commented on compute-testing-info
> +        # bash ./get-changed-test-files $TEMP_DIR 2>&1 | tee -a changedTestFiles.txt
taking this out we might not have time to get to it so let's park it so it doesn't waste that much time

2019-11-21 03:56 UTC, jregchiu approved these changes

2019-11-21 17:31 UTC, merged